config/routes.rb
Pinchlist::Application.routes.draw do
  root to: "home#index"
  namespace :api, defaults: { format: 'json' } do
    resources :lists, only: [:create, :update, :destroy] do
      resources :tasks, :only => [:index, :create, :update, :destroy]
    end
    resources :shares, only: [:create, :destroy]
  end

  get "about" => "pages#about"
  get "terms" => "pages#legal"
  get "help" => "pages#help"

  devise_for :users, :controllers => { :registrations => "registrations" }
  resource :account, only: [:edit, :update]
  resources :users, only: [:update]

  devise_scope :user do
    root to: "dashboards#show", as: :dashboard_root
  end


  post "/stripe/invoice" => "invoices#create"

  get 'dashboard', to: 'dashboards#show', as: :dashboard
  resources :lists, :only => [:show, :create, :update, :destroy] do
    resources :tasks, :only => [:create, :update], :shallow => true
    resource :proxy, :controller => :list_proxies, :only => [:update, :destroy]
    resource :share, :only => [:create, :destroy]
    resource :lock, :only => [:update]
  end

  namespace :public do
    get "lists/:id/:slug" => "lists#show", as: :list
  end

  resources :tasks, :only => [:update]
  resource :subscription, :except => [:edit]
  resource :resubscription, :only => [:create]

  namespace :admin do
    resource :dashboard
    resources :users
  end
end

app/models/list.rb
require 'securerandom'

class List < ActiveRecord::Base
  SUBSCRIBED_LIMIT = 3

  attr_accessor :new_position
  acts_as_list scope: :user

  belongs_to :user, counter_cache: true
  belongs_to :list_base
  has_many :tasks, through: :list_base, before_add: :set_list_base_id

  before_create :ensure_within_limit
  before_create :set_color
  before_create :set_public_token
  before_validation :set_list_base

  after_destroy :notify_list_base
  before_save :set_slug

  validates_associated :list_base
  validates :title, presence: true
  validates :list_base_id, presence: true

  delegate :shares, :shared?, to: :list_base

  def self.current_tasks
    active_date = 7.days.ago.to_date
   where(["(tasks.completed_at IS NULL OR tasks.completed_at > ?)", active_date])
  end

  def self.by_task_status
   order("lists.position ASC, tasks.completed ASC, tasks.position ASC")
  end

  def shares
    list_base.lists.reject{ |list| list.id == id }.map { |list| { id: list.id, email: list.user.email } }
  end

  def shared_users
    list_base.users.where(["users.id != ?", user_id])
  end

  def share_with(user)
    shared_list = dup
    shared_list.user_id = user.id
    shared_list.save
    shared_list
  end

  def self.by_position
    order("position ASC")
  end

  def new_position=(position)
    self.insert_at(position)
  end

  def owned_by?(user)
    owner == user
  end

  def owner
    self.list_base.user
  end

  def generate_public_token
    set_public_token
    save
  end

  def self.public_from_params(params)
    where(public: true, public_token: params[:id], slug: params[:slug]).first!
  end

  def toggle_public
    self.public = !self.public
    save
  end

  private

  def set_public_token
    if self.public_token.nil?
      begin
        self.public_token = SecureRandom.hex(5)
      end while List.exists?(slug: title.parameterize, public_token: self.public_token)
    end
  end

  def set_color
    self.color ||= "%06x" % (rand * 0xffffff)
  end

  def set_slug
    self.slug = title.parameterize
  end

  def notify_list_base
    self.list_base.check_for_lists
  end

  def set_list_base
    if list_base_id.nil?
      self.list_base = ListBase.create(user: user)
    end
  end

  def set_list_base_id(task)
    task.list_base = list_base
  end

  def ensure_within_limit
    unless user.subscribed?
      if user.lists.count >= SUBSCRIBED_LIMIT
        errors.add(:base, "Upgrade to create more lists.")
      end
    end
  end

end

app/controllers/api/lists_controller.rb
class Api::ListsController < Api::BaseController
  respond_to :json

  def index
    lists = current_user.lists.by_position.includes(:list_base)
    respond_with lists
  end

  def create
    respond_with List.create(new_list_params)
  end

  def update
    list = current_user.lists.find(params[:id])
    list.update_attributes(edit_list_params)
    render json: list.reload
  end

  def destroy
    list = current_user.lists.find(params[:id])
    list.destroy
    respond_with list
  end

  private

  def new_list_params
    list_params.merge(user: current_user)
  end

  def edit_list_params
    if params[:new_position]
      list_params.merge(new_position: params[:new_position])
    else
      list_params
    end
  end

  def list_params
    params.
      require(:list).
      permit(:title, :color, :public)
  end
end

app/views/lists/_list.html.haml
%td[list]
  .list_title{:"data-background-color" => list.color, :style => "background-color: ##{list.color};"}
    %h3= list.title
    = link_to 'share', '#', :class => "share_link"
    = render 'sharing'
    .picker
    = link_to 'delete list', list, :method => :delete, :confirm => "Are you sure you want to delete #{list.title}?", :class => 'delete', :tabindex => "-1"
  = form_for [list, Task.new], :remote => true, :html => { :class => 'newtask', :id => "new_task_#{list.id}" } do |form|
    = form.text_field :title, :id => "new_task_title_#{list.id}", :autocomplete => "off", :maxlength => "500"
  %ul.tasks
    = render list.tasks
  = link_to 'view all', list_path(list), :class => "archive_link", :tabindex => "-1"

app/views/lists/show.html.haml
#header
  %h1
    = link_to image_tag('logo-large.png'), root_url
  %ul#util
    %li
      %a{:href => "pages/help", :tabindex => "-1"} Help
    %li= link_to 'Sign Out', destroy_user_session_path, :tabindex => "-1"
    %li.username= link_to current_user.email, edit_user_registration_path, :tabindex => "-1"
#container
  %table{:cellpadding => "0", :cellspacing => "0"}
    %tr
      =render @list, :filter => nil