config/routes.rb
Pinchlist::Application.routes.draw do
  root to: "home#index"
  namespace :api, defaults: { format: 'json' } do
    resources :lists, only: [:create, :update, :destroy] do
      resources :tasks, :only => [:index, :create, :update, :destroy]
    end
    resources :shares, only: [:create, :destroy]
  end

  get "about" => "pages#about"
  get "terms" => "pages#legal"
  get "help" => "pages#help"

  devise_for :users, :controllers => { :registrations => "registrations" }
  resource :account, only: [:edit, :update]
  resources :users, only: [:update]

  devise_scope :user do
    root to: "dashboards#show", as: :dashboard_root
  end


  post "/stripe/invoice" => "invoices#create"

  get 'dashboard', to: 'dashboards#show', as: :dashboard
  resources :lists, :only => [:show, :create, :update, :destroy] do
    resources :tasks, :only => [:create, :update], :shallow => true
    resource :proxy, :controller => :list_proxies, :only => [:update, :destroy]
    resource :share, :only => [:create, :destroy]
    resource :lock, :only => [:update]
  end

  namespace :public do
    get "lists/:id/:slug" => "lists#show", as: :list
  end

  resources :tasks, :only => [:update]
  resource :subscription, :except => [:edit]
  resource :resubscription, :only => [:create]

  namespace :admin do
    resource :dashboard
    resources :users
  end
end

app/helpers/list_proxies_helper.rb
module ListProxiesHelper
end

app/views/list_proxies/_list_proxy.html.haml
%td[list_proxy.list]{:class => list_proxy.shared? ? "shared_list" : nil}
  .list_title{:"data-background-color" => list_proxy.color, :style => "background-color: ##{list_proxy.color};"}
    %h3= list_proxy.title
    .icons{:"data-background-color" => list_proxy.color, :style => "background-color: ##{list_proxy.color};"}
    = link_to 'share', '#', :class => "share_link"
    = render 'sharing', :list_proxy => list_proxy
    .picker
    = link_to 'list actions', "#", :class => "list_actions_link"
    .list_actions
      %ul
        %li
          = link_to 'History', list_archive_path(:list_id => list_proxy.list_id), :class => "list_link archive_link", :tabindex => "-1"
        %li
          = link_to 'Public URL', public_list_path(list_proxy.public_token, slug: list_proxy.slug), :class => "list_link public_link #{list_proxy.public ? 'unlocked' : 'locked'}", :tabindex => "-1"
          = link_to "lock", list_lock_path(list_proxy), class: "public_link_toggle #{list_proxy.public ? "unlocked" : "locked"}", method: :put, remote: true
        %li
          %a.list_link{:href => "#"} Hide List
        %li.delete
          = link_to 'Delete List', list_proxy_path(:list_id => list_proxy.list_id), :method => :delete, :confirm => "Are you sure you want to delete #{list_proxy.title}?", :tabindex => "-1"
  = form_for [list_proxy.list, Task.new], :remote => true, :html => { :class => 'newtask', :id => "new_task_#{list_proxy.list_id}" } do |form|
    = form.text_field :title, :id => "new_task_title_#{list_proxy.list_id}", :autocomplete => "off", :maxlength => "500"
  %ul.tasks{ :data => { :id => list_proxy.list_id } }
    = render list_proxy.tasks.filtered(filter).by_position

app/views/list_proxies/show.html.haml
#header
  %h1
    = link_to image_tag('logo-small.png'), root_url
  %ul#util
    %li
      %a{:href => "pages/help", :tabindex => "-1"} Help
    %li= link_to 'Sign Out', destroy_user_session_path, :tabindex => "-1"
    %li.username= link_to current_user.email, edit_user_registration_path, :tabindex => "-1"
#container
  %table{:cellpadding => "0", :cellspacing => "0"}
    %tr
      =render @list_proxy, :filter => nil